### ISSUE TITLE
User cannot be unset

### ISSUE THREAD

**Issue by fabb** [optimizely/react-sdk#130]
Once the user has been set, it cannot be unset anymore (e.g. for the case the user logged out or withdrew GDPR consent).

Neither `user={undefined}` nor `user={{id: null}}` work because of this code:

<img width="538" alt="Screenshot 2021-10-27 at 16 47 01" src="https://user-images.githubusercontent.com/153960/139093246-ed13b338-3136-4386-99ac-9231d021dc0e.png">

<img width="643" alt="Screenshot 2021-10-27 at 16 52 06" src="https://user-images.githubusercontent.com/153960/139093263-6ec758ba-01ad-43f6-a5b9-283224a59363.png">

**Comment by Danny-Driscoll** [comment]
@fabb Currently within the SDK we require some string ID value in order to be able for the decision and tracking apis to function. We don't currently support functional use or generating a fallback ID ourselves in these cases within the SDK and need that passed-in string value. 

Longer term we would consider handling anonymous users more directly out of the box, but currently for this case we would recommend overwriting the user to a specific new ID value. This could be an anonymous ID you have access to client-side, or even a fixed string value if you are just looking to have basic On/Off toggling available for Features in this state.

**Comment by Develliot** [comment]
I default to a string and then when I run experiments I filter out the user(s) with that string
