### ISSUE TITLE
SSR react-rails window is not defined error

### ISSUE THREAD

**Issue by joshunger** [optimizely/react-sdk#161]
We're consuming `react-sdk` via SSR using `react-rails` and we're getting `window is not defined` Any steps on how to consume `react-sdk` with SSR enabled? This is how `react-rails` does SSR https://github.com/reactjs/react-rails#server-side-rendering

**Comment by opti-jnguyen** [comment]
Thanks for raising this issue @joshunger - will chat with the team on the best way to approach using Optimizely with SSR and reply when we come up with a recommended approach.

Some potential options may include attempting to use Optimizely's underlying Node JavaScript SDK instead of the Browser SDK, or refrain from using the React Optimizely Provider during server-side rendering and instead keep its usage to client-side rendering only.

cc: @zashraf1985

**Comment by joshunger** [comment]
@opti-jnguyen @zashraf1985 thank you! My thought is `react-rails` doesn't really import your bundle correctly? If you have time I'd love some help if you could review the `react-rails` does SSR and see if it supports your library.

**Comment by zashraf1985** [comment]
@joshunger Thanks for raising the issue. It will be helpful if you can provide a working sample that demonstrates this issue. Thanks for your patience.

**Comment by joshunger** [comment]
@zashraf1985 Sure! How about I send you the SSR bundle rails generates in a vanilla project?

**Comment by zashraf1985** [comment]
This works for us with a standard react-rails project. If you have any specific use case, feel free to open a new issue with explanation. Closing this one.
