### ISSUE TITLE
 Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by ManuViola77** [optimizely/react-sdk#180]
Hi. 

I'm getting this `Can't perform a React state update on an unmounted component` Warning when I'm using optimizely.  In a simple example, I created a hook like this:

```
import { useDecision } from '@optimizely/react-sdk';

const useOptimizelyFlag = flag => {
  const [decision] = useDecision(flag);

  return {
    isEnabled: decision.enabled,
  };
};

export default useOptimizelyFlag;
```

And then in my code when I use it like this: 
`const { isEnabled } = useOptimizelyFlag(MY_FLAG);`

then I get the warning I mentioned. If I delete that line and just put `const isEnabled = true` then I don't get the warning anymore. 

Also, the warning I see on screen is telling me is in the optimizely code. 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/8755889/184242909-0123d8cd-48a3-4d7c-b547-8deca6735739.png">

I already checked [this issue](https://github.com/optimizely/react-sdk/issues/17) but it doesn't seem to relate to this particular case now.

Oh, and I tried updating to the last version (right now that's 2.9.1) but didn't help

**Comment by mikechu-optimizely** [comment]
I created an internal bug ticket (FSSDK-9622) to review.

**Comment by junaed-optimizely** [comment]
@ManuViola77 sorry for the delayed response. Its been a while..

There have been some hook udpate in #273 to address some of the rendering issues related to hooks. Could you please update to latest version (3.2.2 right now) and recheck if the issue still persists! 

If persists, could you please provide some implementation details (if possible) on how and where are you using `useOptimizelyFlag` hook so that I can reproduce it? 

Thanks!

**Comment by marcosfilho-hotmart** [comment]
I'm having a similar issue using the `3.2.2` version and react 18

<img width="456" alt="image" src="https://github.com/user-attachments/assets/aab62bf6-893a-4ace-ae8a-fb69d4a65eaf">

I consume Optimizely via a custom-hook "useOptimizely"

![image](https://github.com/user-attachments/assets/fabd8428-b938-4e09-a2bb-ad49503f1b0e)

Use the returned provider and client on a component

![image](https://github.com/user-attachments/assets/f7d6f79f-3ca6-40c7-9c4a-cb9312c8aa20)

And call useDecision on a child component. The hook works fine, but it warns about cleanup of assynchronous tasks

![image](https://github.com/user-attachments/assets/127487bb-62dc-44fd-9e7e-f6566d808ca1)

**Comment by junaed-optimizely** [comment]
Hey @marcosfilho-hotmart, I think you are facing this issue due to the way you are creating Optimizely instance in your custom `useOptimizley` hook.

Every time the parent component gets re-rendered, (in your case its the `Card` component) `useOptimizely` returns a new instance of Optimizely client. 

To mitigate this, you can update your `useOptimizely` hook like following - 

```js
function useOptimizely() {
  const [optimizelyClient] = useState(() => createInstance({
    sdkKey: SDK_KEY,
    eventBatchSize: 10,
    eventFlushInterval: 1000,
  }));

  return { OptimizelyProvider, optimizelyClient };
}
```
This way `useState`  hook will preserve the optimizely instance between re-renders.

Let me know if it helps your case! 

Thanks!

**Comment by marcosfilho-hotmart** [comment]
Thanks for the answer @junaed-optimizely !

First off, as this might be a different issue from the main thread, would you like me to create a new issue?

The error persisted after making the changes suggested on your message, in fact the error started happening on every render instead of only ocasionaly. When executing manual tests locally, the error only happens when `useDecision` is called on child component of an OptimizelyProvider, if I remove it the error does not happen. Just for the sake of it, I have also tried extracting the optimize instance definition outside of the hook and the issue continues to happen.

![image](https://github.com/user-attachments/assets/bcb5f702-c4d8-4e69-8c03-d2880ea8c272)

**Comment by junaed-optimizely** [comment]
@marcosfilho-hotmart , thanks for providing more detail on this.  I will come back to this after some investigation!

**Comment by junaed-optimizely** [comment]
Hi @marcosfilho-hotmart,

Here’s what I found about the warning and the `useDecision` hook:

The `useDecision` hook waits for certain promises to resolve. If the component unmounts before the promise resolves, this warning can appear.

Before React 18, this was considered a potential memory leak. However, the warning was removed in React 18 because it was often misleading. You can find more details in this explanation by Dan: [React 18 Discussion](https://github.com/reactwg/react-18/discussions/82).

I recommend checking if both react and react-dom are updated to React 18.

Hope this helps!

Thanks!

**Comment by marcosfilho-hotmart** [comment]
Thanks for the update, that is indeed most likely the issue as the project is legacy and is still using React 17. We will be updating the application in the following weeks, but its great to know that this is not an actual memory leak. 

Thank you again for the support and for the incredible work with Optimizely!
