### ISSUE TITLE
React SDK does not work. Datafile returns empty.

### ISSUE THREAD

**Issue by nucks** [optimizely/react-sdk#9]
![image](https://user-images.githubusercontent.com/18559697/66418453-612ee780-e9bf-11e9-8850-458adb2fcf97.png)

I can view the datafile from the browser but when I try and use it in the SDK, I receive the error above. I've tried initiating it with both the `sdkKey` and `datafile` but neither works.

My code is simple. Here's the `OptimizelyProvider`:
```
<OptimizelyProvider
  optimizely={optimizely}
  user={{ id: 'user123' }}
>
```

And here's `optimizely`: 
```
const optimizely = createInstance({
  sdkKey: 'secret',
});
```

**Comment by nucks** [comment]
For anyone who runs into these errors...It was happening because I am using the Brave browser and have cross-site shields up. When I turned them off, everything worked as it should.

**Comment by colinhemphill** [comment]
@nucks to piggyback on that, Optimizely has documentation around adblockers/tracking blockers.

https://help.optimizely.com/Troubleshoot_Problems/Troubleshooting%3A_How_ad_blockers_can_affect_Optimizely

We've found that we cannot use the automatic datafile loading features because that's typically what triggers blocking for our end users. When the datafile is loaded from our own servers, we don't typically run into any issues.

**Comment by nucks** [comment]
@colinhemphill thanks for pointing that out!
